export const defaultAdmin = {
  name: 'System Admin',
  email: 'admin@quiz.com',
  password: 'admin123',
  role: 'admin',
};

export const initialQuizzes = [
  {
    title: 'Full-Stack JavaScript Mastery',
    description: 'Test your core concepts in JavaScript ES6+, asynchronous programming, closures, promises, and event loop.',
    category: 'JavaScript',
    difficulty: 'Medium',
    durationMinutes: 10,
    passingScore: 70,
    questions: [
      {
        questionText: 'What is the output of `console.log(typeof NaN)`?',
        options: ['"number"', '"nan"', '"undefined"', '"object"'],
        correctOptionIndex: 0,
        explanation: 'In JavaScript, `NaN` stands for "Not-a-Number", but its data type is actually defined as number.',
        points: 10,
      },
      {
        questionText: 'Which keyword creates a block-scoped variable that cannot be re-assigned?',
        options: ['var', 'let', 'const', 'static'],
        correctOptionIndex: 2,
        explanation: '`const` creates a block-scoped variable whose value cannot be reassigned after declaration.',
        points: 10,
      },
      {
        questionText: 'What is the purpose of the Promise.all() method?',
        options: [
          'Executes promises in sequential order one by one',
          'Resolves when all input promises have resolved, or rejects if any promise rejects',
          'Returns only the fastest resolving promise',
          'Cancels all ongoing async network calls',
        ],
        correctOptionIndex: 1,
        explanation: 'Promise.all() takes an iterable of promises and returns a single Promise that resolves when all input promises resolve.',
        points: 10,
      },
      {
        questionText: 'What will `[1, 2, 3] + [4, 5, 6]` evaluate to in JavaScript?',
        options: ['[1, 2, 3, 4, 5, 6]', '"1,2,34,5,6"', 'NaN', 'TypeError'],
        correctOptionIndex: 1,
        explanation: 'The + operator coerces arrays to strings via .toString(), resulting in "1,2,3" + "4,5,6" = "1,2,34,5,6".',
        points: 10,
      },
    ],
  },
  {
    title: 'React 19 & Modern Web Fundamentals',
    description: 'Challenge your knowledge on Hooks, Virtual DOM, State Management, and component lifecycle.',
    category: 'React',
    difficulty: 'Hard',
    durationMinutes: 12,
    passingScore: 75,
    questions: [
      {
        questionText: 'What hook should be used to perform side effects in functional components?',
        options: ['useState', 'useSideEffect', 'useEffect', 'useMemo'],
        correctOptionIndex: 2,
        explanation: '`useEffect` lets you synchronize a component with an external system and perform side effects after rendering.',
        points: 10,
      },
      {
        questionText: 'Why should keys be provided when rendering lists of elements in React?',
        options: [
          'Keys give elements unique custom CSS styling',
          'Keys help React identify which items have changed, been added, or removed efficiently',
          'Keys automatically serialize data for backend API saving',
          'Keys make the component render synchronously',
        ],
        correctOptionIndex: 1,
        explanation: 'Keys give elements a stable identity so React can optimize DOM diffing during re-renders.',
        points: 10,
      },
      {
        questionText: 'Which hook returns a memoized callback function?',
        options: ['useCallback', 'useMemo', 'useRef', 'useImperativeHandle'],
        correctOptionIndex: 0,
        explanation: '`useCallback` caches a function definition between renders, while `useMemo` caches the result of a calculation.',
        points: 10,
      },
      {
        questionText: 'What happens when `setState` is called inside a component?',
        options: [
          'React reloads the whole browser window immediately',
          'React schedules a component re-render to update the user interface',
          'React mutates the DOM directly without diffing',
          'React deletes the component state permanently',
        ],
        correctOptionIndex: 1,
        explanation: '`setState` triggers a re-render cycle where React computes virtual DOM updates and updates the real DOM.',
        points: 10,
      },
    ],
  },
  {
    title: 'Data Structures & Algorithms Basics',
    description: 'Test fundamental DSA concepts including Time Complexity, Trees, Sorting, and Big O Notation.',
    category: 'Data Structures',
    difficulty: 'Medium',
    durationMinutes: 15,
    passingScore: 60,
    questions: [
      {
        questionText: 'What is the worst-case time complexity of QuickSort?',
        options: ['O(N log N)', 'O(N)', 'O(N^2)', 'O(log N)'],
        correctOptionIndex: 2,
        explanation: 'QuickSort has a worst-case time complexity of O(N^2) when the pivot selection leads to unbalanced splits.',
        points: 10,
      },
      {
        questionText: 'Which data structure operates on a First In, First Out (FIFO) principle?',
        options: ['Stack', 'Queue', 'Tree', 'Graph'],
        correctOptionIndex: 1,
        explanation: 'A Queue processes elements in First In, First Out (FIFO) order, similar to a physical line of people.',
        points: 10,
      },
      {
        questionText: 'What is the time complexity to search an item in a balanced Binary Search Tree (BST)?',
        options: ['O(1)', 'O(log N)', 'O(N)', 'O(N log N)'],
        correctOptionIndex: 1,
        explanation: 'In a balanced BST, each comparison eliminates half the remaining tree nodes, resulting in O(log N) operations.',
        points: 10,
      },
    ],
  },
  {
    title: 'MongoDB & Backend Architecture',
    description: 'Evaluate your knowledge of MongoDB document modeling, indexing, aggregation, and RESTful APIs.',
    category: 'Backend & DB',
    difficulty: 'Easy',
    durationMinutes: 8,
    passingScore: 60,
    questions: [
      {
        questionText: 'What format does MongoDB use to store data documents internally?',
        options: ['JSON text', 'BSON (Binary JSON)', 'XML', 'CSV'],
        correctOptionIndex: 1,
        explanation: 'MongoDB stores records internally as BSON, a binary representation of JSON-like documents.',
        points: 10,
      },
      {
        questionText: 'Which HTTP method is typically used to create a new resource in a RESTful API?',
        options: ['GET', 'PUT', 'POST', 'DELETE'],
        correctOptionIndex: 2,
        explanation: '`POST` is standard for submitting data to create a new resource on the server.',
        points: 10,
      },
      {
        questionText: 'What is the default primary key field name automatically created by MongoDB?',
        options: ['id', '_id', 'uuid', 'primaryKey'],
        correctOptionIndex: 1,
        explanation: 'MongoDB automatically assigns an ObjectId to the `_id` field for every inserted document if not specified.',
        points: 10,
      },
    ],
  },
];
